.\"                                      Hey, EMACS: -*- nroff -*-
.TH REGEXXER 1 "November 11, 2002"
.SH NAME
regexxer \- visual regular expression search and replace
.SH SYNOPSIS
.B regexxer
.SH DESCRIPTION
This manual page documents briefly the
.B regexxer
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
\fBregexxer\fP is a program that allows you to select a group of
files, and perform perl-style regular expression search and replace
operations to the files, in an interactive graphical interface.
.SH SEE ALSO
.BR perlre (1).
.br
.SH AUTHOR
This manual page was written by Ross Burton <ross@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
